# Generated by Django 4.2.28 on 2026-04-02 09:01

from django.db import migrations


def seed_general_department_and_profiles(apps, schema_editor):
    Department = apps.get_model('tasks', 'Department')
    EmployeeProfile = apps.get_model('tasks', 'EmployeeProfile')
    User = apps.get_model('auth', 'User')

    general_dept, _ = Department.objects.get_or_create(name='General')

    for user in User.objects.all():
        EmployeeProfile.objects.get_or_create(user=user, defaults={'department': general_dept})

def reverse_seed(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_department_employeeprofile'),
    ]

    operations = [
        migrations.RunPython(seed_general_department_and_profiles, reverse_seed),
    ]
